### ISSUE TITLE
How to display policy text?

### ISSUE THREAD

**Issue by CSixtyFour** [krzysztofgal/GravGdprPrivacySetupPlugin#1]
Hi
Thanks for the really useful plugin.

I think I need to display the content of the different policies (cookie, privacy, etc) before a user can accept otherwise they don't really know what they're agreeing to but I've already got a policies page with the text and formating etc so I don't really want to have maintain the same content in two places.

Maybe we could have a page whitelist so certain pages can be allowed to load without accepting?

I tried to load my page within the Content -> Privacy Information using this technique `{% include 'page_reuse.html.twig' with {'page': page.find('/pages/policies')} %}` but I get my code literally rendered on the page, is there a way to pull the contents from another page through to be displayed?
Thanks

**Comment by krzysztofgal** [comment]
Hi

You can setup in settings "Url for page containing privacy info and form" url to Your policy page **but** it will be loaded into modal as full page. with navbars etc... that is reason I put content of popup to "Privacy Information" in plugin.

Content -> Privacy Information: there is only markdown with html allowed.

"Maybe we could have a page whitelist so certain pages can be allowed to load without accepting?" - Yes, that`s my oversight. Next week I will add feature to whitelist selected pages to not show popup.

Anyway intention of this plugin is to display some short straightfoward information about site policy and this information should have a link to full version of site policy.

**Comment by CSixtyFour** [comment]
Ah I didn't see the "Url for page containing privacy info and form" option - that has worked to bring through my text but it is also unscrollable so I can read the whole page and also I don't get the accept / decline buttons (probably pushed way down to the bottom of the page).

I think the way to go is a short description and the tick box rather than the whole policy in the modal as you say.

**Comment by krzysztofgal** [comment]
version 0.0.4, You have now page whitelist feature.
