### ISSUE TITLE
Plugin installation on a Grav website brakes the website

### ISSUE THREAD

**Issue by djdakta** [krzysztofgal/GravGdprPrivacySetupPlugin#10]
I started the installation of the plugin using the 'Plugins' module in the admin panel of my Grav website, after a few seconds an error occurred which broke my website. :-(
See screenshot for the error message.
![screen shot 2018-12-18 at 19 28 09](https://user-images.githubusercontent.com/6761835/50195875-33e64f80-0341-11e9-87f2-2df13bbede44.png)

I was able to solve the problem by correcting the error in the gdprprivacysetup.php file.
I created a pr with the correction made to the file for your convenience. :-)

**Comment by n3bojs4** [comment]
Same issue i can't use it it breaks the website error 500.

**Comment by krzysztofgal** [comment]
You should use at least PHP 7.1 at this moment.

**Comment by SamGe** [comment]
When installing the GDPR Privacy Setup Plugin from within the graphical admin gui, the Website and the admin content won't load at all. No 404 or anything. The nginx error.log says:

<code>2019/03/14 20:04:46 [error] 796#796: 14052 FastCGI sent in stderr: "PHP message: PHP Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /home/grav/www/html/user/plugins/gdprprivacysetup/gdprprivacysetup.php on line 30" while reading response header from upstream, client: 95.91.212.104, server: Mywebsite com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "Mywebsite com" @@@</code>

Deleting the plugin from the server manually will result in instant availability of the Website Content again.

Grav v1.5.8 - Admin v1.8.19 and PHP 7.2.15
