### ISSUE TITLE
Can't install plugin on Grav 1.5.6 .PHP 5.6 

### ISSUE THREAD

**Issue by marcgarciajr** [krzysztofgal/GravGdprPrivacySetupPlugin#12]
Once I installed the plugin my site crashed and I have the following log error:

`2019/06/26 02:45:18 [error] 15#15: *111052 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/grav-admin/user/plugins/gdprprivacysetup/gdprprivacysetup.php on line 30" while reading response header from upstream, client: 66.249.73.221, server: sogematech.com, request: "GET /fr/projets-phares HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", hos`

On Grav 1.5.6 PHP 5.6

**Comment by krzysztofgal** [comment]
Plugin works with PHP 7.1. You may fork plugin and change `private const` to `const`, then it should work with PHP 5.6
