### ISSUE TITLE
Cuts-Off Page Content

### ISSUE THREAD

**Issue by oldmanumby** [krzysztofgal/GravGdprPrivacySetupPlugin#2]
Great plugin, however, it is cutting off the right edge of the page content. Suggestions?

<img width="1171" alt="screen shot 2018-06-26 at 11 36 31 am" src="https://user-images.githubusercontent.com/22547499/41926584-6547728e-7935-11e8-89fe-fb557a13fe66.png">

**Comment by krzysztofgal** [comment]
Hi

This looks more like theme css issue. You can try to fix this by adding custom styles to privacy page content.

I`m not a css specialist to know from screen which property cause that content behawior. I can look at it if You give me site address.
