### ISSUE TITLE
Parse error: syntax error, unexpected '?' in /user/plugins/gdprprivacysetup/gdprprivacysetup.php on line 165

### ISSUE THREAD

**Issue by pnkr** [krzysztofgal/GravGdprPrivacySetupPlugin#3]
Hi, when installing your plugin i get the above error.
The problem is in: 
`

    private function isAllowed($consent)

    {

        if (!isset($this->userConsent[$consent])) {
            //fallback for new consents, that are not in cookie
            $this->userConsent[$consent] = $this->csp[$consent] ?? false;
        }

        return (bool) $this->userConsent[$consent];
    }
`
In line 165 what you try to do is not a php valid code. May be you mean?
$this->userConsent[$consent] = isset($this->csp[$consent]) ? $this->csp[$consent] : false;

**Comment by krzysztofgal** [comment]
Hi

You need php 7. Grav will soon require php 7 too, at this point no one should using php 5. But maybe I will fix this to be php 5 compatibile in next version.

**Comment by krzysztofgal** [comment]
fix in version 0.0.6.
