### ISSUE TITLE
Is there a way to reduce the width of the white box? and button sizes?

### ISSUE THREAD

**Issue by mannp** [krzysztofgal/GravGdprPrivacySetupPlugin#5]
Many thanks for the plugin :)

I am finding the box containing the buttons to be rather large and wondered if I am able to reduce its size, in order to make every much more compact?

Thanks in advance

**Comment by krzysztofgal** [comment]
Hi.

For now You have only option on Content tab to change classes for buttons "Consent button class", "Deny button class".

Box appearance comes from [tingle](https://robinparisi.github.io/tingle/) lib, and content styling comes from Your theme css.
