### ISSUE TITLE
Json Encode "&quot;" issue

### ISSUE THREAD

**Issue by ClixStudios** [krzysztofgal/GravGdprPrivacySetupPlugin#7]
Please forgive my primitive knowledge of Grav and PHP, but after installing the GravGdprPrivacySetupPlugin in to a Gantry5 themed Grav site, I'm getting the console warning of "SyntaxError: expected property name, got '&'".

var gdprPrivacySetupPluginSettings = {
    ..........
    ..........
    userConsent: {&quot;site&quot;:true,&quot;webfonts&quot;:false,&quot;analytics&quot;:false}
};

All I can do is point out that on (gdprprivacysetup.php line: 203) has a json_encode. I used the "JSON_UNESCAPED_UNICODE" (http://php.net/manual/en/function.json-encode.php) But this produced no difference.

https://github.com/krzysztofgal/GravGdprPrivacySetupPlugin/blob/be076e6d4061709f3f6e634bfb6db135f34f12c3/gdprprivacysetup.php#L203

**Comment by krzysztofgal** [comment]
I will look into Gantry5 issues at the weekend.

**Comment by ClixStudios** [comment]
Thank you! It may well be the same issue as: https://github.com/krzysztofgal/GravGdprPrivacySetupPlugin/issues/6#issue-357017049

**Comment by krzysztofgal** [comment]
v 0.1.0 - plugin now work with Hydrogen (Gantry5) theme.
Issue was caused by no proper Twig encoding.
